services:
  line:
    build:
      context: ./line
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}"
    ports:
      - "${PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./line/bin:/app

  pgadmin:
    image: dpage/pgadmin4:8.13.0
    container_name: "${PROJECT_NAME}_pgadmin"
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
