services:
  line:
    build:
      context: ./line
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}"
    ports:
      - "${PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./line/bin:/app
